version: "3.4"

services:
  php:
    container_name: php
    build: .docker
    volumes:
      - ../..:/var/www/html
      - exclude:/var/www/html/plugins/EscapioEventsExporter/.docker
      - ./config.ini.php:/var/www/html/config/config.ini.php
    depends_on: [db]
    user: "${UID}:${GID}"
    ports:
      - "${MATOMO_PORT:-9000}:9000"
    command: ["php", "-S", "0.0.0.0:9000"]

  db:
    image: mariadb:10.11.2
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - ./.docker/volumes/db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_DBNAME}
      - MARIADB_USER=${DATABASE_USERNAME}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}

  test_db:
    image: mariadb:10.11.2
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - ./.docker/volumes/test_db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=test_db_root_pw
      - MARIADB_DATABASE=test_db
      - MARIADB_USER=test_db_user
      - MARIADB_PASSWORD=test_db_pw

volumes:
  exclude:
